# Generated by Django 2.0.3 on 2018-03-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_name',
            new_name='minister_name',
        ),
    ]
