# Generated by Django 2.0.3 on 2018-03-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180322_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='minister_name',
            new_name='province_name',
        ),
    ]
