# Generated by Django 2.0.3 on 2018-03-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180322_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_type',
            new_name='minister_name',
        ),
    ]
