# Generated by Django 2.0.3 on 2018-03-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180322_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='categories',
            new_name='districts',
        ),
    ]
