# Generated by Django 2.0.3 on 2018-03-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180322_0827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Provinces',
        ),
    ]
