# Generated by Django 2.0.3 on 2018-03-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180322_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinces',
            name='districts',
            field=models.IntegerField(max_length=50),
        ),
    ]
