# Generated by Django 2.0.3 on 2018-03-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180322_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinces',
            name='districts',
            field=models.IntegerField(),
        ),
    ]
